# Generated by Django 5.2.4 on 2025-07-28 17:54

import embed_video.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('project_desc', models.CharField(max_length=2000)),
                ('project_image', models.ImageField(default='project_pictures/genericproject.jpg', upload_to='project_pictures/')),
                ('project_url', models.URLField(blank=True, max_length=400, null=True)),
                ('project_video', embed_video.fields.EmbedVideoField(blank=True, null=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='projects', to='Projects.tag')),
            ],
        ),
    ]
